// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { AlertDialog } from "@next-app/ui-kit";

const meta = {
  title: "Design System/Alert Dialog",
  component: AlertDialog,
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta<typeof AlertDialog>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<AlertDialog />),
};

export const RelatedPreview: Story = {
  render: () => (<AlertDialog />),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
