// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { Avatar } from "@next-app/ui-kit";

const meta = {
  title: "Design System/Avatar",
  component: Avatar,
  args: {
    fallback: "A",
    radius: "full",
    size: "3",
  },
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta<typeof Avatar>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<Avatar fallback="A" radius="full" size="3" />),
};

export const RelatedPreview: Story = {
  render: () => (<Avatar fallback="A" radius="full" size="3" />),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
