// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { portalPreviewCatalogBySlug } from "@/lib/storybook/portal-preview-catalog";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { Avatar } from "@next-app/ui-kit";

export const portalPreviewCatalog = portalPreviewCatalogBySlug["avatar"];

const meta = {
  title: "Design System/Avatar",
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<Avatar fallback="A" radius="full" size="3" />),
};

export const RelatedPreview: Story = {
  render: () => (<Avatar fallback="A" radius="full" size="3" />),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
