// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { Blockquote } from "@next-app/ui-kit";

const meta = {
  title: "Design System/Blockquote",
  component: Blockquote,
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta<typeof Blockquote>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<Blockquote>Design systems scale consistency.</Blockquote>),
};

export const RelatedPreview: Story = {
  render: () => (<Blockquote>Design systems scale consistency.</Blockquote>),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
