// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { ContextMenu } from "@next-app/ui-kit";

const meta = {
  title: "Design System/Context Menu",
  component: ContextMenu,
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta<typeof ContextMenu>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<ContextMenu />),
};

export const RelatedPreview: Story = {
  render: () => (<ContextMenu />),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
