// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { Text } from "@radix-ui/themes";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { Container } from "@next-app/ui-kit";

const meta = {
  title: "Design System/Container",
  component: Container,
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta<typeof Container>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<Container size="2"><Text>Container</Text></Container>),
};

export const RelatedPreview: Story = {
  render: () => (<Container size="2"><Text>Container</Text></Container>),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
