// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { DropdownMenu } from "@next-app/ui-kit";

const meta = {
  title: "Design System/Dropdown Menu",
  component: DropdownMenu,
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta<typeof DropdownMenu>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<DropdownMenu />),
};

export const RelatedPreview: Story = {
  render: () => (<DropdownMenu />),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
