// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { portalPreviewCatalogBySlug } from "@/lib/storybook/portal-preview-catalog";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { Heading } from "@next-app/ui-kit";

export const portalPreviewCatalog = portalPreviewCatalogBySlug["heading"];

const meta = {
  title: "Design System/Heading",
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<Heading size="5">Heading</Heading>),
};

export const RelatedPreview: Story = {
  render: () => (<Heading size="5">Heading</Heading>),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
