// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { Progress } from "@next-app/ui-kit";

const meta = {
  title: "Design System/Progress",
  component: Progress,
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta<typeof Progress>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<Progress value={60} />),
};

export const RelatedPreview: Story = {
  render: () => (<Progress value={60} style={{ width: 240 }} />),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
