// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { Flex, Text } from "@radix-ui/themes";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { Radio } from "@next-app/ui-kit";

const meta = {
  title: "Design System/Radio",
  component: Radio,
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta<typeof Radio>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<Flex align="center" gap="2"><Radio name="demo" value="a" defaultChecked /> <Text size="2">Option</Text></Flex>),
};

export const RelatedPreview: Story = {
  render: () => (<Flex align="center" gap="2"><Radio name="preview" value="a" defaultChecked /> <Text size="2">Radio</Text></Flex>),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
