// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { Text } from "@radix-ui/themes";
import { portalPreviewCatalogBySlug } from "@/lib/storybook/portal-preview-catalog";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { ScrollArea } from "@next-app/ui-kit";

export const portalPreviewCatalog = portalPreviewCatalogBySlug["scroll-area"];

const meta = {
  title: "Design System/Scroll Area",
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<ScrollArea type="always" scrollbars="vertical" style={{ height: 120, width: 240 }}><Text as="p" size="2">Scrollable content line 1<br />Line 2<br />Line 3<br />Line 4</Text></ScrollArea>),
};

export const RelatedPreview: Story = {
  render: () => (<ScrollArea type="always" scrollbars="vertical" style={{ height: 120, width: 240 }}><Text as="p" size="2">Scrollable content</Text></ScrollArea>),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
