// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { Text } from "@radix-ui/themes";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { Section } from "@next-app/ui-kit";

const meta = {
  title: "Design System/Section",
  component: Section,
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta<typeof Section>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<Section size="2"><Text>Section</Text></Section>),
};

export const RelatedPreview: Story = {
  render: () => (<Section size="2"><Text>Section</Text></Section>),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
