// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { Spinner } from "@next-app/ui-kit";

const meta = {
  title: "Design System/Spinner",
  component: Spinner,
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta<typeof Spinner>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<Spinner />),
};

export const RelatedPreview: Story = {
  render: () => (<Spinner />),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
