// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { Text } from "@radix-ui/themes";
import { portalPreviewCatalogBySlug } from "@/lib/storybook/portal-preview-catalog";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { Strong } from "@next-app/ui-kit";

export const portalPreviewCatalog = portalPreviewCatalogBySlug["strong"];

const meta = {
  title: "Design System/Strong",
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<Text><Strong>Strong</Strong> label</Text>),
};

export const RelatedPreview: Story = {
  render: () => (<Text><Strong>Strong</Strong> label</Text>),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
