// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { Flex, Text } from "@radix-ui/themes";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { Switch } from "@next-app/ui-kit";

const meta = {
  title: "Design System/Switch",
  component: Switch,
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta<typeof Switch>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<Flex align="center" gap="2"><Switch defaultChecked /><Text size="2">Enabled</Text></Flex>),
};

export const RelatedPreview: Story = {
  render: () => (<Flex align="center" gap="2"><Switch defaultChecked /><Text size="2">Switch</Text></Flex>),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
