// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { Text } from "@next-app/ui-kit";

const meta = {
  title: "Design System/Text",
  component: Text,
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta<typeof Text>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (<Text size="3">Body text</Text>),
};

export const RelatedPreview: Story = {
  render: () => (<Text size="3">Body text</Text>),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
