/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    components: Component;
    colors: Color;
    icons: Icon;
    notes: Note;
    'field-showcase': FieldShowcase;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'components';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    components: ComponentsSelect<false> | ComponentsSelect<true>;
    colors: ColorsSelect<false> | ColorsSelect<true>;
    icons: IconsSelect<false> | IconsSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    'field-showcase': FieldShowcaseSelect<false> | FieldShowcaseSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'portal-sources': PortalSource;
  };
  globalsSelect: {
    'portal-sources': PortalSourcesSelect<false> | PortalSourcesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  /**
   * Права пользователя в CMS.
   */
  role: 'admin' | 'viewer' | 'designer' | 'developer' | 'pm';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Карточка и ссылки; вкладка «Документация» — блоки для портала (визуал на сайте). Все типы полей Payload — коллекция «Справочник полей».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "components".
 */
export interface Component {
  id: number;
  name: string;
  /**
   * Латиница, без пробелов — страница портала /components/[slug]
   */
  slug: string;
  /**
   * Лид под заголовком на портале.
   */
  description?: string | null;
  figmaUrl?: string | null;
  storybookUrl?: string | null;
  docsUrl?: string | null;
  status?: ('stable' | 'beta' | 'deprecated' | 'draft') | null;
  /**
   * Текст бейджа или предупреждения на портале.
   */
  statusNote?: string | null;
  /**
   * Вариант или часть семейства (отдельная страница-родитель).
   */
  parentComponent?: (number | null) | Component;
  /**
   * Дочерние компоненты со своими страницами в портале.
   */
  subcomponents?: (number | Component)[] | null;
  /**
   * Смежные компоненты (часто используют вместе).
   */
  relatedComponents?: (number | Component)[] | null;
  /**
   * Для deprecated — куда перейти вместо этого компонента.
   */
  replacedBy?: (number | null) | Component;
  /**
   * Правая колонка «На этой странице». Список строится из заголовков H2 на странице.
   */
  showTOC?: boolean | null;
  /**
   * Все 24 типа контент-блоков. Порядок = порядок на портале.
   */
  documentation?:
    | (
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            dos?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            donts?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'doDont';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            tone: 'info' | 'warning' | 'success';
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeExample';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            snippet: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeMonaco';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextSection';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            rows?:
              | {
                  name: string;
                  type: string;
                  defaultValue?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'propsTable';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'resourceLinks';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaFigure';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            color?: (number | null) | Color;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relColor';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            icon?: (number | null) | Icon;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relIcon';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            label?: string | null;
            /**
             * @minItems 2
             * @maxItems 2
             */
            location?: [number, number] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'geoPoint';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            at?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calendarDate';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            label?: string | null;
            address?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'emailLine';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            label?: string | null;
            value?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'numberStat';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            mode?: ('fast' | 'normal' | 'precise') | null;
            hint?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'radioPick';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            tags?: ('a11y' | 'forms' | 'layout' | 'motion')[] | null;
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'multiSelect';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            enabled?: boolean | null;
            flagLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'flagBox';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            payload?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'jsonBlock';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            bundle?: {
              gTitle?: string | null;
              gCount?: number | null;
              gOn?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'groupStrip';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            intro?: string | null;
            items?:
              | {
                  /**
                   * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
                   */
                  showLLM?: boolean | null;
                  line: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'nestLine';
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'nestedStack';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            tabSummary?: ComponentDocTabSummary;
            tabDetail?: ComponentDocTabDetail;
            id?: string | null;
            blockName?: string | null;
            blockType: 'namedTabsStrip';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            body: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title: string;
            /**
             * Ссылка на story с args, скопированная из Storybook. Пример: http://127.0.0.1:6006/?path=/story/design-system-button--default&args=variant:secondary;size:sm — не /docs/…
             */
            storybookUrl: string;
            frameHeight?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'storybookEmbed';
          }
      )[]
    | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
}
/**
 * Цветовые токены / образцы палитры; вкладка «Документация» — те же 24 блока, что у components.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  name: string;
  /**
   * Например color.primary или palette.blue.500
   */
  tokenKey?: string | null;
  /**
   * #RRGGBB
   */
  hex: string;
  sortOrder?: number | null;
  caption?: string | null;
  /**
   * 8 типов блоков для документации цвета (секция, заметка, rich text, код, Do/Don't, ссылки, изображение, связанный цвет).
   */
  documentation?:
    | (
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            tone: 'info' | 'warning' | 'success';
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextSection';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeExample';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            dos?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            donts?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'doDont';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'resourceLinks';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaFigure';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            color?: (number | null) | Color;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relColor';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Иконки: метаданные и ссылки; превью — через Media.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons".
 */
export interface Icon {
  id: number;
  name: string;
  slug?: string | null;
  preview?: (number | null) | Media;
  figmaUrl?: string | null;
  storybookUrl?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComponentDocTabSummary".
 */
export interface ComponentDocTabSummary {
  brief?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComponentDocTabDetail".
 */
export interface ComponentDocTabDetail {
  detail?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'components';
          value: number | Component;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'components'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  title: string;
  body?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Один документ на команду: все типы полей данных Payload (array, blocks, checkbox, code, …) для ориентира в админке.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-showcase".
 */
export interface FieldShowcase {
  id: number;
  title: string;
  demoText?: string | null;
  demoTextarea?: string | null;
  demoNumber?: number | null;
  demoCheckbox?: boolean | null;
  demoEmail?: string | null;
  demoDate?: string | null;
  demoRadio?: ('a' | 'b') | null;
  demoSelect?: ('red' | 'green' | 'blue')[] | null;
  demoCode?: string | null;
  demoJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  demoPoint?: [number, number] | null;
  demoRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  demoRelationship?: (number | null) | Color;
  demoUpload?: (number | null) | Media;
  demoArray?:
    | {
        label: string;
        count?: number | null;
        id?: string | null;
      }[]
    | null;
  demoGroup?: {
    groupTitle?: string | null;
    groupNote?: string | null;
  };
  demoBlocks?:
    | (
        | {
            key: string;
            value?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'line';
          }
        | {
            label: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tag';
          }
      )[]
    | null;
  tabMeta?: FieldShowcaseTabMeta;
  tabMetrics?: FieldShowcaseTabMetrics;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FieldShowcaseTabMeta".
 */
export interface FieldShowcaseTabMeta {
  metaSlug?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FieldShowcaseTabMetrics".
 */
export interface FieldShowcaseTabMetrics {
  score?: number | null;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  colors?: {
    /**
     * Allow clients to find colors.
     */
    find?: boolean | null;
    /**
     * Allow clients to create colors.
     */
    create?: boolean | null;
    /**
     * Allow clients to update colors.
     */
    update?: boolean | null;
  };
  icons?: {
    /**
     * Allow clients to find icons.
     */
    find?: boolean | null;
    /**
     * Allow clients to create icons.
     */
    create?: boolean | null;
    /**
     * Allow clients to update icons.
     */
    update?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
  };
  notes?: {
    /**
     * Allow clients to find notes.
     */
    find?: boolean | null;
    /**
     * Allow clients to create notes.
     */
    create?: boolean | null;
    /**
     * Allow clients to update notes.
     */
    update?: boolean | null;
  };
  portalSources?: {
    /**
     * Allow clients to find portal-sources global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update portal-sources global.
     */
    update?: boolean | null;
  };
  'payload-mcp-tool'?: {
    /**
     * Карточка UI-компонента (components): name, slug, description, ссылки. Без documentation. Укажи slug или id.
     */
    getComponent?: boolean | null;
    /**
     * Список карточек UI-компонентов (name, slug, description, ссылки). Без documentation.
     */
    listComponents?: boolean | null;
    /**
     * Полный список коллекции components: все поля, documentation только с блоками, у которых в CMS включён showLLM. Большой ответ; для карточки — listComponents.
     */
    listComponentsFull?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'components';
        value: number | Component;
      } | null)
    | ({
        relationTo: 'colors';
        value: number | Color;
      } | null)
    | ({
        relationTo: 'icons';
        value: number | Icon;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'field-showcase';
        value: number | FieldShowcase;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "components_select".
 */
export interface ComponentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  figmaUrl?: T;
  storybookUrl?: T;
  docsUrl?: T;
  status?: T;
  statusNote?: T;
  parentComponent?: T;
  subcomponents?: T;
  relatedComponents?: T;
  replacedBy?: T;
  showTOC?: T;
  documentation?:
    | T
    | {
        section?:
          | T
          | {
              showLLM?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        doDont?:
          | T
          | {
              showLLM?: T;
              dos?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              donts?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              showLLM?: T;
              tone?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        codeExample?:
          | T
          | {
              showLLM?: T;
              title?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        codeMonaco?:
          | T
          | {
              showLLM?: T;
              title?: T;
              snippet?: T;
              id?: T;
              blockName?: T;
            };
        richTextSection?:
          | T
          | {
              showLLM?: T;
              title?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        propsTable?:
          | T
          | {
              showLLM?: T;
              title?: T;
              rows?:
                | T
                | {
                    name?: T;
                    type?: T;
                    defaultValue?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        resourceLinks?:
          | T
          | {
              showLLM?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaFigure?:
          | T
          | {
              showLLM?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        relColor?:
          | T
          | {
              showLLM?: T;
              color?: T;
              id?: T;
              blockName?: T;
            };
        relIcon?:
          | T
          | {
              showLLM?: T;
              icon?: T;
              id?: T;
              blockName?: T;
            };
        geoPoint?:
          | T
          | {
              showLLM?: T;
              label?: T;
              location?: T;
              id?: T;
              blockName?: T;
            };
        calendarDate?:
          | T
          | {
              showLLM?: T;
              title?: T;
              at?: T;
              id?: T;
              blockName?: T;
            };
        emailLine?:
          | T
          | {
              showLLM?: T;
              label?: T;
              address?: T;
              id?: T;
              blockName?: T;
            };
        numberStat?:
          | T
          | {
              showLLM?: T;
              label?: T;
              value?: T;
              id?: T;
              blockName?: T;
            };
        radioPick?:
          | T
          | {
              showLLM?: T;
              mode?: T;
              hint?: T;
              id?: T;
              blockName?: T;
            };
        multiSelect?:
          | T
          | {
              showLLM?: T;
              tags?: T;
              note?: T;
              id?: T;
              blockName?: T;
            };
        flagBox?:
          | T
          | {
              showLLM?: T;
              enabled?: T;
              flagLabel?: T;
              id?: T;
              blockName?: T;
            };
        jsonBlock?:
          | T
          | {
              showLLM?: T;
              title?: T;
              payload?: T;
              id?: T;
              blockName?: T;
            };
        groupStrip?:
          | T
          | {
              showLLM?: T;
              bundle?:
                | T
                | {
                    gTitle?: T;
                    gCount?: T;
                    gOn?: T;
                  };
              id?: T;
              blockName?: T;
            };
        nestedStack?:
          | T
          | {
              showLLM?: T;
              intro?: T;
              items?:
                | T
                | {
                    nestLine?:
                      | T
                      | {
                          showLLM?: T;
                          line?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        namedTabsStrip?:
          | T
          | {
              showLLM?: T;
              tabSummary?: T | ComponentDocTabSummarySelect<T>;
              tabDetail?: T | ComponentDocTabDetailSelect<T>;
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              showLLM?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              showLLM?: T;
              body?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        storybookEmbed?:
          | T
          | {
              showLLM?: T;
              title?: T;
              storybookUrl?: T;
              frameHeight?: T;
              id?: T;
              blockName?: T;
            };
      };
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComponentDocTabSummary_select".
 */
export interface ComponentDocTabSummarySelect<T extends boolean = true> {
  brief?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComponentDocTabDetail_select".
 */
export interface ComponentDocTabDetailSelect<T extends boolean = true> {
  detail?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  name?: T;
  tokenKey?: T;
  hex?: T;
  sortOrder?: T;
  caption?: T;
  documentation?:
    | T
    | {
        section?:
          | T
          | {
              showLLM?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              showLLM?: T;
              tone?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        richTextSection?:
          | T
          | {
              showLLM?: T;
              title?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        codeExample?:
          | T
          | {
              showLLM?: T;
              title?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        doDont?:
          | T
          | {
              showLLM?: T;
              dos?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              donts?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        resourceLinks?:
          | T
          | {
              showLLM?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaFigure?:
          | T
          | {
              showLLM?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        relColor?:
          | T
          | {
              showLLM?: T;
              color?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons_select".
 */
export interface IconsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  preview?: T;
  figmaUrl?: T;
  storybookUrl?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-showcase_select".
 */
export interface FieldShowcaseSelect<T extends boolean = true> {
  title?: T;
  demoText?: T;
  demoTextarea?: T;
  demoNumber?: T;
  demoCheckbox?: T;
  demoEmail?: T;
  demoDate?: T;
  demoRadio?: T;
  demoSelect?: T;
  demoCode?: T;
  demoJson?: T;
  demoPoint?: T;
  demoRichText?: T;
  demoRelationship?: T;
  demoUpload?: T;
  demoArray?:
    | T
    | {
        label?: T;
        count?: T;
        id?: T;
      };
  demoGroup?:
    | T
    | {
        groupTitle?: T;
        groupNote?: T;
      };
  demoBlocks?:
    | T
    | {
        line?:
          | T
          | {
              key?: T;
              value?: T;
              id?: T;
              blockName?: T;
            };
        tag?:
          | T
          | {
              label?: T;
              id?: T;
              blockName?: T;
            };
      };
  tabMeta?: T | FieldShowcaseTabMetaSelect<T>;
  tabMetrics?: T | FieldShowcaseTabMetricsSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FieldShowcaseTabMeta_select".
 */
export interface FieldShowcaseTabMetaSelect<T extends boolean = true> {
  metaSlug?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FieldShowcaseTabMetrics_select".
 */
export interface FieldShowcaseTabMetricsSelect<T extends boolean = true> {
  score?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  colors?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  icons?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  notes?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  portalSources?:
    | T
    | {
        find?: T;
        update?: T;
      };
  'payload-mcp-tool'?:
    | T
    | {
        getComponent?: T;
        listComponents?: T;
        listComponentsFull?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Общие URL: библиотека Figma, Storybook, репозиторий, внешняя документация.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-sources".
 */
export interface PortalSource {
  id: number;
  figmaLibraryUrl?: string | null;
  storybookUrl?: string | null;
  documentationUrl?: string | null;
  repositoryUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-sources_select".
 */
export interface PortalSourcesSelect<T extends boolean = true> {
  figmaLibraryUrl?: T;
  storybookUrl?: T;
  documentationUrl?: T;
  repositoryUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}