/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    components: Component;
    'design-checklist-items': DesignChecklistItem;
    'glossary-terms': GlossaryTerm;
    'brand-pages': BrandPage;
    'ds-pages': DsPage;
    colors: Color;
    icons: Icon;
    notes: Note;
    'field-showcase': FieldShowcase;
    search: Search;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'components';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    components: ComponentsSelect<false> | ComponentsSelect<true>;
    'design-checklist-items': DesignChecklistItemsSelect<false> | DesignChecklistItemsSelect<true>;
    'glossary-terms': GlossaryTermsSelect<false> | GlossaryTermsSelect<true>;
    'brand-pages': BrandPagesSelect<false> | BrandPagesSelect<true>;
    'ds-pages': DsPagesSelect<false> | DsPagesSelect<true>;
    colors: ColorsSelect<false> | ColorsSelect<true>;
    icons: IconsSelect<false> | IconsSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    'field-showcase': FieldShowcaseSelect<false> | FieldShowcaseSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'portal-sources': PortalSource;
    'portal-seo': PortalSeo;
    'text-glossary': TextGlossary;
    'brand-overview': BrandOverview;
    'ds-overview': DsOverview;
  };
  globalsSelect: {
    'portal-sources': PortalSourcesSelect<false> | PortalSourcesSelect<true>;
    'portal-seo': PortalSeoSelect<false> | PortalSeoSelect<true>;
    'text-glossary': TextGlossarySelect<false> | TextGlossarySelect<true>;
    'brand-overview': BrandOverviewSelect<false> | BrandOverviewSelect<true>;
    'ds-overview': DsOverviewSelect<false> | DsOverviewSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  /**
   * Права пользователя в CMS.
   */
  role: 'admin' | 'viewer' | 'designer' | 'developer' | 'pm';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Карточка и ссылки; вкладка «Документация» — блоки для портала (визуал на сайте). Все типы полей Payload — коллекция «Справочник полей».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "components".
 */
export interface Component {
  id: number;
  name: string;
  /**
   * Латиница, без пробелов — страница портала /components/[slug]
   */
  slug: string;
  /**
   * Лид под заголовком на портале.
   */
  description?: string | null;
  figmaUrl?: string | null;
  storybookUrl?: string | null;
  /**
   * Скриншот для карточек Related Components. Генерация: npm run capture:related-previews
   */
  relatedPreviewLight?: (number | null) | Media;
  /**
   * Скриншот для карточек Related Components в тёмной теме портала.
   */
  relatedPreviewDark?: (number | null) | Media;
  docsUrl?: string | null;
  /**
   * Не заполнены обязательные поля карточки — запись не попадает на портал (черновик в CMS без отдельного статуса).
   */
  status?: ('stable' | 'beta' | 'deprecated') | null;
  /**
   * Текст бейджа или предупреждения на портале.
   */
  statusNote?: string | null;
  /**
   * Вариант или часть семейства (отдельная страница-родитель).
   */
  parentComponent?: (number | null) | Component;
  /**
   * Дочерние компоненты со своими страницами в портале.
   */
  subcomponents?: (number | Component)[] | null;
  /**
   * Смежные компоненты (часто используют вместе).
   */
  relatedComponents?: (number | Component)[] | null;
  /**
   * Для deprecated — куда перейти вместо этого компонента.
   */
  replacedBy?: (number | null) | Component;
  /**
   * Правая колонка «На этой странице». Список строится из заголовков H2 на странице.
   */
  showTOC?: boolean | null;
  /**
   * Список заполняется автоматически. Редактору нужно только включить «Выполнено».
   */
  designChecklist?:
    | {
        /**
         * Подставляется из справочника автоматически.
         */
        item: number | DesignChecklistItem;
        done?: boolean | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 13 типов контент-блоков (14-й слот — Markdown export на странице). Порядок = порядок на портале.
   */
  documentation?:
    | (
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            heading: string;
            /**
             * Абзац под заголовком (when to use, guidelines).
             */
            body?: string | null;
            /**
             * Варианты, свойства или правила — с цветным маркером слева.
             */
            items?:
              | {
                  label: string;
                  description?: string | null;
                  accentColor?: string | null;
                  labelAsBadge?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            /**
             * Например: Button Props, Modal.Content Props.
             */
            subtitle?: string | null;
            rows?:
              | {
                  name: string;
                  type: string;
                  defaultValue?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'propsTable';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title: string;
            /**
             * Story с args: ?path=/story/design-system-button--default&args=variant:secondary
             */
            storybookUrl: string;
            frameHeight?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'storybookEmbed';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            /**
             * Опциональный iframe над кодом — как на HeroUI.
             */
            previewStorybookUrl?: string | null;
            previewHeight?: number | null;
            code: string;
            defaultCollapsed?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeExample';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            heading?: string | null;
            intro?: string | null;
            dos?:
              | {
                  text: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            donts?:
              | {
                  text: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'doDont';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            /**
             * Например: соответствие WAI-ARIA Dialog pattern.
             */
            intro?: string | null;
            patternLinkLabel?: string | null;
            patternLinkUrl?: string | null;
            keyboardRows?:
              | {
                  keys: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'accessibility';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            components?: (number | Component)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relComponents';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            groups?:
              | {
                  groupTitle: string;
                  helpUrl?: string | null;
                  rows?:
                    | {
                        name: string;
                        description?: string | null;
                        valueType?: ('string' | 'number' | 'color') | null;
                        defaultValue?: string | null;
                        swatchColor?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'designTokens';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            entries?:
              | {
                  version: string;
                  kind?: ('patch' | 'minor' | 'major') | null;
                  changes?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'changelog';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            image: number | Media;
            parts?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'anatomy';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  done?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checklist';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'resourceLinks';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            intro?: string | null;
            tokens?:
              | {
                  name: string;
                  description?: string | null;
                  value: string;
                  /**
                   * Необязательно, для подписи в UI.
                   */
                  durationMs?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'motion';
          }
      )[]
    | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
}
/**
 * Общие требования к компонентам. На карточке каждого компонента отмечайте выполнение.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-checklist-items".
 */
export interface DesignChecklistItem {
  id: number;
  title: string;
  description?: string | null;
  category?: ('states' | 'accessibility' | 'layout' | 'content') | null;
  sortOrder?: number | null;
  /**
   * Снято — пункт скрыт на всех страницах компонентов.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'components';
          value: number | Component;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'components'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Слова для интерфейса и коммуникации с пользователями. Список сгруппирован по букве (латиница, затем кириллица).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms".
 */
export interface GlossaryTerm {
  id: number;
  /**
   * Правильное слово или формулировка для интерфейса и текстов.
   */
  preferred: string;
  /**
   * Неправильные варианты через запятую — на портале показываются перечёркнутыми.
   */
  avoid?: string | null;
  /**
   * Первая буква «Используем» — для группировки (EN, затем RU).
   */
  letter?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Контент страниц /brand/*: логотипы, иконки, типографика, палитра.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-pages".
 */
export interface BrandPage {
  id: number;
  slug: 'logos' | 'icons' | 'typography' | 'color';
  sortOrder?: number | null;
  title: string;
  description: string;
  intro: string;
  sections?:
    | (
        | {
            /**
             * Латиница и дефис, например logo-background.
             */
            sectionId: string;
            heading?: string | null;
            blocks?:
              | (
                  | {
                      text: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'subheading';
                    }
                  | {
                      text: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'paragraph';
                    }
                  | {
                      items?:
                        | {
                            text: string;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'list';
                    }
                  | {
                      src: string;
                      alt: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'figure';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentBlocks';
          }
        | {
            /**
             * Необязательный якорь для всей секции.
             */
            sectionId?: string | null;
            items: {
              anchorId: string;
              heading: string;
              blocks?:
                | (
                    | {
                        text: string;
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'subheading';
                      }
                    | {
                        text: string;
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'paragraph';
                      }
                    | {
                        items?:
                          | {
                              text: string;
                              id?: string | null;
                            }[]
                          | null;
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'list';
                      }
                    | {
                        src: string;
                        alt: string;
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'figure';
                      }
                  )[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentAccordion';
          }
        | {
            sectionId: string;
            heading: string;
            groups: {
              groupId: string;
              title: string;
              rows: {
                name: string;
                fontSize: number;
                lineHeight: number;
                letterSpacing: number;
                weight: number;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'typographyScale';
          }
        | {
            sectionId: string;
            heading: string;
            desktopLabel: string;
            downloadHref: string;
            downloadLabel: string;
            cssLabel: string;
            cssCode: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fontSetup';
          }
        | {
            sectionId: string;
            heading: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'colorSystem';
          }
        | {
            sectionId: string;
            heading: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'colorGradients';
          }
        | {
            sectionId: string;
            heading: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'colorChartPalette';
          }
        | {
            sectionId: string;
            heading: string;
            rules: {
              label: string;
              surface: 'light' | 'dark';
              logoSrc: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoBackgroundGrid';
          }
        | {
            sectionId: string;
            heading: string;
            items: {
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoClearspace';
          }
        | {
            sectionId: string;
            heading: string;
            intro?: string | null;
            items: {
              imageSrc: string;
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoMisuseGrid';
          }
      )[]
    | null;
  /**
   * Если пусто — используется заголовок страницы.
   */
  shareTitle?: string | null;
  /**
   * Если пусто — используется описание страницы.
   */
  shareDescription?: string | null;
  hierarchyBase?: {
    title?: string | null;
    description?: string | null;
    tokens?:
      | {
          name: string;
          hex: string;
          id?: string | null;
        }[]
      | null;
  };
  hierarchySemantic?: {
    title?: string | null;
    description?: string | null;
    tokens?:
      | {
          name: string;
          hex: string;
          id?: string | null;
        }[]
      | null;
  };
  hierarchyComponent?: {
    title?: string | null;
    description?: string | null;
    tokens?:
      | {
          name: string;
          hex: string;
          id?: string | null;
        }[]
      | null;
  };
  hierarchyMappings?:
    | {
        from: string;
        to: string;
        id?: string | null;
      }[]
    | null;
  semanticsSections?:
    | {
        title: string;
        body: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  semanticsNamingParts?:
    | {
        part: string;
        required?: boolean | null;
        examples?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  semanticsExamples?:
    | {
        token: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  componentTokensIntro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  componentTokensNamingParts?:
    | {
        part: string;
        examples?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  componentTokensExamples?:
    | {
        token: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  gradients?:
    | {
        gradientId: string;
        title: string;
        angle?: number | null;
        stops: {
          hex: string;
          rgb: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  chartPaletteLightLabel?: string | null;
  chartPaletteLight?:
    | {
        hex: string;
        rgb: string;
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  chartPaletteDarkLabel?: string | null;
  chartPaletteDark?:
    | {
        hex: string;
        rgb: string;
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Вложенные страницы /ds/* (например /ds/introduction). Дерево и drag-and-drop — в списке коллекции.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ds-pages".
 */
export interface DsPage {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Латиница, без слэшей. Итоговый путь строится из цепочки родителей: /ds/introduction или /ds/guides/basics.
   */
  slug: string;
  description?: string | null;
  /**
   * Блоки документации — тот же набор, что у components.
   */
  documentation?:
    | (
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            heading: string;
            /**
             * Абзац под заголовком (when to use, guidelines).
             */
            body?: string | null;
            /**
             * Варианты, свойства или правила — с цветным маркером слева.
             */
            items?:
              | {
                  label: string;
                  description?: string | null;
                  accentColor?: string | null;
                  labelAsBadge?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            /**
             * Например: Button Props, Modal.Content Props.
             */
            subtitle?: string | null;
            rows?:
              | {
                  name: string;
                  type: string;
                  defaultValue?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'propsTable';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title: string;
            /**
             * Story с args: ?path=/story/design-system-button--default&args=variant:secondary
             */
            storybookUrl: string;
            frameHeight?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'storybookEmbed';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            /**
             * Опциональный iframe над кодом — как на HeroUI.
             */
            previewStorybookUrl?: string | null;
            previewHeight?: number | null;
            code: string;
            defaultCollapsed?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeExample';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            heading?: string | null;
            intro?: string | null;
            dos?:
              | {
                  text: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            donts?:
              | {
                  text: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'doDont';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            /**
             * Например: соответствие WAI-ARIA Dialog pattern.
             */
            intro?: string | null;
            patternLinkLabel?: string | null;
            patternLinkUrl?: string | null;
            keyboardRows?:
              | {
                  keys: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'accessibility';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            components?: (number | Component)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relComponents';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            groups?:
              | {
                  groupTitle: string;
                  helpUrl?: string | null;
                  rows?:
                    | {
                        name: string;
                        description?: string | null;
                        valueType?: ('string' | 'number' | 'color') | null;
                        defaultValue?: string | null;
                        swatchColor?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'designTokens';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            entries?:
              | {
                  version: string;
                  kind?: ('patch' | 'minor' | 'major') | null;
                  changes?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'changelog';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            image: number | Media;
            parts?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'anatomy';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  done?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checklist';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'resourceLinks';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            intro?: string | null;
            tokens?:
              | {
                  name: string;
                  description?: string | null;
                  value: string;
                  /**
                   * Необязательно, для подписи в UI.
                   */
                  durationMs?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'motion';
          }
      )[]
    | null;
  parent?: (number | null) | DsPage;
  breadcrumbs?:
    | {
        doc?: (number | null) | DsPage;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Цветовые токены / образцы палитры; вкладка «Документация» — те же 24 блока, что у components.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  name: string;
  /**
   * Например color.primary или palette.blue.500
   */
  tokenKey?: string | null;
  /**
   * #RRGGBB
   */
  hex: string;
  sortOrder?: number | null;
  caption?: string | null;
  /**
   * 8 типов блоков для документации цвета (секция, заметка, rich text, код, Do/Don't, ссылки, изображение, связанный цвет).
   */
  documentation?:
    | (
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            heading: string;
            /**
             * Абзац под заголовком (when to use, guidelines).
             */
            body?: string | null;
            /**
             * Варианты, свойства или правила — с цветным маркером слева.
             */
            items?:
              | {
                  label: string;
                  description?: string | null;
                  accentColor?: string | null;
                  labelAsBadge?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            heading?: string | null;
            intro?: string | null;
            dos?:
              | {
                  text: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            donts?:
              | {
                  text: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'doDont';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            /**
             * Опциональный iframe над кодом — как на HeroUI.
             */
            previewStorybookUrl?: string | null;
            previewHeight?: number | null;
            code: string;
            defaultCollapsed?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeExample';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'resourceLinks';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            groups?:
              | {
                  groupTitle: string;
                  helpUrl?: string | null;
                  rows?:
                    | {
                        name: string;
                        description?: string | null;
                        valueType?: ('string' | 'number' | 'color') | null;
                        defaultValue?: string | null;
                        swatchColor?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'designTokens';
          }
        | {
            /**
             * Включено — блок попадает в ответ MCP для LLM. На портале блок показывается всегда.
             */
            showLLM?: boolean | null;
            title?: string | null;
            /**
             * Например: Button Props, Modal.Content Props.
             */
            subtitle?: string | null;
            rows?:
              | {
                  name: string;
                  type: string;
                  defaultValue?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'propsTable';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Иконки: метаданные и ссылки; превью — через Media.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons".
 */
export interface Icon {
  id: number;
  name: string;
  slug?: string | null;
  preview?: (number | null) | Media;
  figmaUrl?: string | null;
  storybookUrl?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  title: string;
  body?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Один документ на команду: все типы полей данных Payload (array, blocks, checkbox, code, …) для ориентира в админке.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-showcase".
 */
export interface FieldShowcase {
  id: number;
  title: string;
  demoText?: string | null;
  demoTextarea?: string | null;
  demoNumber?: number | null;
  demoCheckbox?: boolean | null;
  demoEmail?: string | null;
  demoDate?: string | null;
  demoRadio?: ('a' | 'b') | null;
  demoSelect?: ('red' | 'green' | 'blue')[] | null;
  demoCode?: string | null;
  demoJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  demoPoint?: [number, number] | null;
  demoRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  demoRelationship?: (number | null) | Color;
  demoUpload?: (number | null) | Media;
  demoArray?:
    | {
        label: string;
        count?: number | null;
        id?: string | null;
      }[]
    | null;
  demoGroup?: {
    groupTitle?: string | null;
    groupNote?: string | null;
  };
  demoBlocks?:
    | (
        | {
            key: string;
            value?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'line';
          }
        | {
            label: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tag';
          }
      )[]
    | null;
  tabMeta?: FieldShowcaseTabMeta;
  tabMetrics?: FieldShowcaseTabMetrics;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FieldShowcaseTabMeta".
 */
export interface FieldShowcaseTabMeta {
  metaSlug?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FieldShowcaseTabMetrics".
 */
export interface FieldShowcaseTabMetrics {
  score?: number | null;
}
/**
 * Индекс для быстрого поиска по документации портала (только заголовок). Записи создаются автоматически при Publish/сохранении исходных коллекций. Кнопка Reindex — для первичной индексации.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'ds-pages';
        value: number | DsPage;
      }
    | {
        relationTo: 'components';
        value: number | Component;
      }
    | {
        relationTo: 'brand-pages';
        value: number | BrandPage;
      }
    | {
        relationTo: 'glossary-terms';
        value: number | GlossaryTerm;
      }
    | {
        relationTo: 'colors';
        value: number | Color;
      };
  /**
   * Нормализованный текст для поиска (см. PORTAL_SEARCH_MATCH_SCOPE).
   */
  searchText?: string | null;
  /**
   * Заголовки, описания и контент блоков документации.
   */
  excerpt?: string | null;
  portalUrl?: string | null;
  area?: ('ds' | 'components' | 'brand' | 'text' | 'colors') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  colors?: {
    /**
     * Allow clients to find colors.
     */
    find?: boolean | null;
    /**
     * Allow clients to create colors.
     */
    create?: boolean | null;
    /**
     * Allow clients to update colors.
     */
    update?: boolean | null;
  };
  icons?: {
    /**
     * Allow clients to find icons.
     */
    find?: boolean | null;
    /**
     * Allow clients to create icons.
     */
    create?: boolean | null;
    /**
     * Allow clients to update icons.
     */
    update?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
  };
  notes?: {
    /**
     * Allow clients to find notes.
     */
    find?: boolean | null;
    /**
     * Allow clients to create notes.
     */
    create?: boolean | null;
    /**
     * Allow clients to update notes.
     */
    update?: boolean | null;
  };
  glossaryTerms?: {
    /**
     * Allow clients to find glossary-terms.
     */
    find?: boolean | null;
    /**
     * Allow clients to create glossary-terms.
     */
    create?: boolean | null;
    /**
     * Allow clients to update glossary-terms.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete glossary-terms.
     */
    delete?: boolean | null;
  };
  brandPages?: {
    /**
     * Allow clients to find brand-pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create brand-pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update brand-pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete brand-pages.
     */
    delete?: boolean | null;
  };
  dsPages?: {
    /**
     * Allow clients to find ds-pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create ds-pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update ds-pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete ds-pages.
     */
    delete?: boolean | null;
  };
  portalSources?: {
    /**
     * Allow clients to find portal-sources global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update portal-sources global.
     */
    update?: boolean | null;
  };
  portalSeo?: {
    /**
     * Allow clients to find portal-seo global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update portal-seo global.
     */
    update?: boolean | null;
  };
  textGlossary?: {
    /**
     * Allow clients to find text-glossary global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update text-glossary global.
     */
    update?: boolean | null;
  };
  brandOverview?: {
    /**
     * Allow clients to find brand-overview global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update brand-overview global.
     */
    update?: boolean | null;
  };
  dsOverview?: {
    /**
     * Allow clients to find ds-overview global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update ds-overview global.
     */
    update?: boolean | null;
  };
  'payload-mcp-tool'?: {
    /**
     * Карточка UI-компонента (components): name, slug, description, ссылки. Без documentation. Укажи slug или id.
     */
    getComponent?: boolean | null;
    /**
     * Список карточек UI-компонентов (name, slug, description, ссылки). Без documentation.
     */
    listComponents?: boolean | null;
    /**
     * Полный список коллекции components: все поля, documentation только с блоками, у которых в CMS включён showLLM. Большой ответ; для карточки — listComponents.
     */
    listComponentsFull?: boolean | null;
    /**
     * For humans/docs: minimal user prompts — only «Через finam-design-system» anchor, no MCP tool names. Call when user asks what to paste in a new Cursor chat.
     */
    getComposeUserPromptGuide?: boolean | null;
    /**
     * MANDATORY FIRST CALL when user asks to build UI through finam-design-system. Returns the current /ds CMS usage guide, planningPolicy, and guidanceRevision. Apply planningPolicy before showing any plan: never promise to reproduce a detected or suspected anti-pattern as-is; say the UI will be corrected through Payload Do/Don't rules. Read and apply guidance before creating Design Brief and calling composeUi.
     */
    resolveComposeIntent?: boolean | null;
    /**
     * PRIMARY after resolveComposeIntent. Loads component Do/Don't rules and UI terminology from Payload. First response returns rules; revise the Design Brief, correcting Figma anti-patterns instead of reproducing them, then repeat with componentGuidanceRevision and mandatory componentAudit describing every corrected component as before → after. Final report lines must be disclosed to the user.
     */
    composeUi?: boolean | null;
    /**
     * Alias of composeUi — prefer composeUi. Uses the same two-pass Payload guidance, corrects Figma anti-patterns instead of reproducing them, and requires mandatory componentAudit report.
     */
    composeFromFigmaContext?: boolean | null;
    /**
     * Compose guide for troubleshooting. For user requests (Figma URL or plain-language UI) use resolveComposeIntent → composeUi automatically — never ask user to name tools.
     */
    getComposeGuide?: boolean | null;
    /**
     * Reference for Figma → compose kinds and parsed fileKey/nodeId. Prefer resolveComposeIntent + composeUi for user-facing requests.
     */
    getFigmaComposeWorkflow?: boolean | null;
    /**
     * Lower-level: Design Brief → Composition JSON only. Prefer composeUi for full TSX output.
     */
    planCompositionFromBrief?: boolean | null;
    /**
     * Registry of @radix-ui/themes components for compose: ids, props, types, defaults. Call getComposeGuide first. Use field `id` as CompositionNode.component. Target package: @radix-ui/themes only.
     */
    getComponentRegistry?: boolean | null;
    /**
     * Validate Composition JSON before render. Returns { valid, issues[] } with JSON paths. Schema: { version: "1", root: { component, props?, text?, children? } }.
     */
    validateComposition?: boolean | null;
    /**
     * Turn valid Composition JSON into TSX importing only @radix-ui/themes. Always run validateComposition first. Returns tsx, imports, componentName, and projectSetup. Agent should post tsx in chat — do not write project files unless the user asks. Do not hand-write Radix JSX.
     */
    renderComposition?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'components';
        value: number | Component;
      } | null)
    | ({
        relationTo: 'design-checklist-items';
        value: number | DesignChecklistItem;
      } | null)
    | ({
        relationTo: 'glossary-terms';
        value: number | GlossaryTerm;
      } | null)
    | ({
        relationTo: 'brand-pages';
        value: number | BrandPage;
      } | null)
    | ({
        relationTo: 'ds-pages';
        value: number | DsPage;
      } | null)
    | ({
        relationTo: 'colors';
        value: number | Color;
      } | null)
    | ({
        relationTo: 'icons';
        value: number | Icon;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'field-showcase';
        value: number | FieldShowcase;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "components_select".
 */
export interface ComponentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  figmaUrl?: T;
  storybookUrl?: T;
  relatedPreviewLight?: T;
  relatedPreviewDark?: T;
  docsUrl?: T;
  status?: T;
  statusNote?: T;
  parentComponent?: T;
  subcomponents?: T;
  relatedComponents?: T;
  replacedBy?: T;
  showTOC?: T;
  designChecklist?:
    | T
    | {
        item?: T;
        done?: T;
        note?: T;
        id?: T;
      };
  documentation?:
    | T
    | {
        section?:
          | T
          | {
              showLLM?: T;
              heading?: T;
              body?: T;
              items?:
                | T
                | {
                    label?: T;
                    description?: T;
                    accentColor?: T;
                    labelAsBadge?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        propsTable?:
          | T
          | {
              showLLM?: T;
              title?: T;
              subtitle?: T;
              rows?:
                | T
                | {
                    name?: T;
                    type?: T;
                    defaultValue?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        storybookEmbed?:
          | T
          | {
              showLLM?: T;
              title?: T;
              storybookUrl?: T;
              frameHeight?: T;
              id?: T;
              blockName?: T;
            };
        codeExample?:
          | T
          | {
              showLLM?: T;
              title?: T;
              previewStorybookUrl?: T;
              previewHeight?: T;
              code?: T;
              defaultCollapsed?: T;
              id?: T;
              blockName?: T;
            };
        doDont?:
          | T
          | {
              showLLM?: T;
              heading?: T;
              intro?: T;
              dos?:
                | T
                | {
                    text?: T;
                    image?: T;
                    id?: T;
                  };
              donts?:
                | T
                | {
                    text?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        accessibility?:
          | T
          | {
              showLLM?: T;
              intro?: T;
              patternLinkLabel?: T;
              patternLinkUrl?: T;
              keyboardRows?:
                | T
                | {
                    keys?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        relComponents?:
          | T
          | {
              showLLM?: T;
              title?: T;
              components?: T;
              id?: T;
              blockName?: T;
            };
        designTokens?:
          | T
          | {
              showLLM?: T;
              title?: T;
              groups?:
                | T
                | {
                    groupTitle?: T;
                    helpUrl?: T;
                    rows?:
                      | T
                      | {
                          name?: T;
                          description?: T;
                          valueType?: T;
                          defaultValue?: T;
                          swatchColor?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        changelog?:
          | T
          | {
              showLLM?: T;
              entries?:
                | T
                | {
                    version?: T;
                    kind?: T;
                    changes?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        anatomy?:
          | T
          | {
              showLLM?: T;
              title?: T;
              image?: T;
              parts?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        checklist?:
          | T
          | {
              showLLM?: T;
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    done?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        resourceLinks?:
          | T
          | {
              showLLM?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        motion?:
          | T
          | {
              showLLM?: T;
              title?: T;
              intro?: T;
              tokens?:
                | T
                | {
                    name?: T;
                    description?: T;
                    value?: T;
                    durationMs?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-checklist-items_select".
 */
export interface DesignChecklistItemsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms_select".
 */
export interface GlossaryTermsSelect<T extends boolean = true> {
  preferred?: T;
  avoid?: T;
  letter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-pages_select".
 */
export interface BrandPagesSelect<T extends boolean = true> {
  slug?: T;
  sortOrder?: T;
  title?: T;
  description?: T;
  intro?: T;
  sections?:
    | T
    | {
        contentBlocks?:
          | T
          | {
              sectionId?: T;
              heading?: T;
              blocks?:
                | T
                | {
                    subheading?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                          blockName?: T;
                        };
                    paragraph?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                          blockName?: T;
                        };
                    list?:
                      | T
                      | {
                          items?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    figure?:
                      | T
                      | {
                          src?: T;
                          alt?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        contentAccordion?:
          | T
          | {
              sectionId?: T;
              items?:
                | T
                | {
                    anchorId?: T;
                    heading?: T;
                    blocks?:
                      | T
                      | {
                          subheading?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                                blockName?: T;
                              };
                          paragraph?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                                blockName?: T;
                              };
                          list?:
                            | T
                            | {
                                items?:
                                  | T
                                  | {
                                      text?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          figure?:
                            | T
                            | {
                                src?: T;
                                alt?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        typographyScale?:
          | T
          | {
              sectionId?: T;
              heading?: T;
              groups?:
                | T
                | {
                    groupId?: T;
                    title?: T;
                    rows?:
                      | T
                      | {
                          name?: T;
                          fontSize?: T;
                          lineHeight?: T;
                          letterSpacing?: T;
                          weight?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fontSetup?:
          | T
          | {
              sectionId?: T;
              heading?: T;
              desktopLabel?: T;
              downloadHref?: T;
              downloadLabel?: T;
              cssLabel?: T;
              cssCode?: T;
              id?: T;
              blockName?: T;
            };
        colorSystem?:
          | T
          | {
              sectionId?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        colorGradients?:
          | T
          | {
              sectionId?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        colorChartPalette?:
          | T
          | {
              sectionId?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        logoBackgroundGrid?:
          | T
          | {
              sectionId?: T;
              heading?: T;
              rules?:
                | T
                | {
                    label?: T;
                    surface?: T;
                    logoSrc?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoClearspace?:
          | T
          | {
              sectionId?: T;
              heading?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoMisuseGrid?:
          | T
          | {
              sectionId?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    imageSrc?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  shareTitle?: T;
  shareDescription?: T;
  hierarchyBase?:
    | T
    | {
        title?: T;
        description?: T;
        tokens?:
          | T
          | {
              name?: T;
              hex?: T;
              id?: T;
            };
      };
  hierarchySemantic?:
    | T
    | {
        title?: T;
        description?: T;
        tokens?:
          | T
          | {
              name?: T;
              hex?: T;
              id?: T;
            };
      };
  hierarchyComponent?:
    | T
    | {
        title?: T;
        description?: T;
        tokens?:
          | T
          | {
              name?: T;
              hex?: T;
              id?: T;
            };
      };
  hierarchyMappings?:
    | T
    | {
        from?: T;
        to?: T;
        id?: T;
      };
  semanticsSections?:
    | T
    | {
        title?: T;
        body?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  semanticsNamingParts?:
    | T
    | {
        part?: T;
        required?: T;
        examples?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  semanticsExamples?:
    | T
    | {
        token?: T;
        description?: T;
        id?: T;
      };
  componentTokensIntro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  componentTokensNamingParts?:
    | T
    | {
        part?: T;
        examples?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  componentTokensExamples?:
    | T
    | {
        token?: T;
        description?: T;
        id?: T;
      };
  gradients?:
    | T
    | {
        gradientId?: T;
        title?: T;
        angle?: T;
        stops?:
          | T
          | {
              hex?: T;
              rgb?: T;
              id?: T;
            };
        id?: T;
      };
  chartPaletteLightLabel?: T;
  chartPaletteLight?:
    | T
    | {
        hex?: T;
        rgb?: T;
        name?: T;
        id?: T;
      };
  chartPaletteDarkLabel?: T;
  chartPaletteDark?:
    | T
    | {
        hex?: T;
        rgb?: T;
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ds-pages_select".
 */
export interface DsPagesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  description?: T;
  documentation?:
    | T
    | {
        section?:
          | T
          | {
              showLLM?: T;
              heading?: T;
              body?: T;
              items?:
                | T
                | {
                    label?: T;
                    description?: T;
                    accentColor?: T;
                    labelAsBadge?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        propsTable?:
          | T
          | {
              showLLM?: T;
              title?: T;
              subtitle?: T;
              rows?:
                | T
                | {
                    name?: T;
                    type?: T;
                    defaultValue?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        storybookEmbed?:
          | T
          | {
              showLLM?: T;
              title?: T;
              storybookUrl?: T;
              frameHeight?: T;
              id?: T;
              blockName?: T;
            };
        codeExample?:
          | T
          | {
              showLLM?: T;
              title?: T;
              previewStorybookUrl?: T;
              previewHeight?: T;
              code?: T;
              defaultCollapsed?: T;
              id?: T;
              blockName?: T;
            };
        doDont?:
          | T
          | {
              showLLM?: T;
              heading?: T;
              intro?: T;
              dos?:
                | T
                | {
                    text?: T;
                    image?: T;
                    id?: T;
                  };
              donts?:
                | T
                | {
                    text?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        accessibility?:
          | T
          | {
              showLLM?: T;
              intro?: T;
              patternLinkLabel?: T;
              patternLinkUrl?: T;
              keyboardRows?:
                | T
                | {
                    keys?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        relComponents?:
          | T
          | {
              showLLM?: T;
              title?: T;
              components?: T;
              id?: T;
              blockName?: T;
            };
        designTokens?:
          | T
          | {
              showLLM?: T;
              title?: T;
              groups?:
                | T
                | {
                    groupTitle?: T;
                    helpUrl?: T;
                    rows?:
                      | T
                      | {
                          name?: T;
                          description?: T;
                          valueType?: T;
                          defaultValue?: T;
                          swatchColor?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        changelog?:
          | T
          | {
              showLLM?: T;
              entries?:
                | T
                | {
                    version?: T;
                    kind?: T;
                    changes?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        anatomy?:
          | T
          | {
              showLLM?: T;
              title?: T;
              image?: T;
              parts?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        checklist?:
          | T
          | {
              showLLM?: T;
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    done?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        resourceLinks?:
          | T
          | {
              showLLM?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        motion?:
          | T
          | {
              showLLM?: T;
              title?: T;
              intro?: T;
              tokens?:
                | T
                | {
                    name?: T;
                    description?: T;
                    value?: T;
                    durationMs?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  name?: T;
  tokenKey?: T;
  hex?: T;
  sortOrder?: T;
  caption?: T;
  documentation?:
    | T
    | {
        section?:
          | T
          | {
              showLLM?: T;
              heading?: T;
              body?: T;
              items?:
                | T
                | {
                    label?: T;
                    description?: T;
                    accentColor?: T;
                    labelAsBadge?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        doDont?:
          | T
          | {
              showLLM?: T;
              heading?: T;
              intro?: T;
              dos?:
                | T
                | {
                    text?: T;
                    image?: T;
                    id?: T;
                  };
              donts?:
                | T
                | {
                    text?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        codeExample?:
          | T
          | {
              showLLM?: T;
              title?: T;
              previewStorybookUrl?: T;
              previewHeight?: T;
              code?: T;
              defaultCollapsed?: T;
              id?: T;
              blockName?: T;
            };
        resourceLinks?:
          | T
          | {
              showLLM?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        designTokens?:
          | T
          | {
              showLLM?: T;
              title?: T;
              groups?:
                | T
                | {
                    groupTitle?: T;
                    helpUrl?: T;
                    rows?:
                      | T
                      | {
                          name?: T;
                          description?: T;
                          valueType?: T;
                          defaultValue?: T;
                          swatchColor?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        propsTable?:
          | T
          | {
              showLLM?: T;
              title?: T;
              subtitle?: T;
              rows?:
                | T
                | {
                    name?: T;
                    type?: T;
                    defaultValue?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons_select".
 */
export interface IconsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  preview?: T;
  figmaUrl?: T;
  storybookUrl?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-showcase_select".
 */
export interface FieldShowcaseSelect<T extends boolean = true> {
  title?: T;
  demoText?: T;
  demoTextarea?: T;
  demoNumber?: T;
  demoCheckbox?: T;
  demoEmail?: T;
  demoDate?: T;
  demoRadio?: T;
  demoSelect?: T;
  demoCode?: T;
  demoJson?: T;
  demoPoint?: T;
  demoRichText?: T;
  demoRelationship?: T;
  demoUpload?: T;
  demoArray?:
    | T
    | {
        label?: T;
        count?: T;
        id?: T;
      };
  demoGroup?:
    | T
    | {
        groupTitle?: T;
        groupNote?: T;
      };
  demoBlocks?:
    | T
    | {
        line?:
          | T
          | {
              key?: T;
              value?: T;
              id?: T;
              blockName?: T;
            };
        tag?:
          | T
          | {
              label?: T;
              id?: T;
              blockName?: T;
            };
      };
  tabMeta?: T | FieldShowcaseTabMetaSelect<T>;
  tabMetrics?: T | FieldShowcaseTabMetricsSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FieldShowcaseTabMeta_select".
 */
export interface FieldShowcaseTabMetaSelect<T extends boolean = true> {
  metaSlug?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FieldShowcaseTabMetrics_select".
 */
export interface FieldShowcaseTabMetricsSelect<T extends boolean = true> {
  score?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  searchText?: T;
  excerpt?: T;
  portalUrl?: T;
  area?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  colors?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  icons?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  notes?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  glossaryTerms?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  brandPages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  dsPages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  portalSources?:
    | T
    | {
        find?: T;
        update?: T;
      };
  portalSeo?:
    | T
    | {
        find?: T;
        update?: T;
      };
  textGlossary?:
    | T
    | {
        find?: T;
        update?: T;
      };
  brandOverview?:
    | T
    | {
        find?: T;
        update?: T;
      };
  dsOverview?:
    | T
    | {
        find?: T;
        update?: T;
      };
  'payload-mcp-tool'?:
    | T
    | {
        getComponent?: T;
        listComponents?: T;
        listComponentsFull?: T;
        getComposeUserPromptGuide?: T;
        resolveComposeIntent?: T;
        composeUi?: T;
        composeFromFigmaContext?: T;
        getComposeGuide?: T;
        getFigmaComposeWorkflow?: T;
        planCompositionFromBrief?: T;
        getComponentRegistry?: T;
        validateComposition?: T;
        renderComposition?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Общие URL: библиотека Figma, Storybook, репозиторий, внешняя документация.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-sources".
 */
export interface PortalSource {
  id: number;
  figmaLibraryUrl?: string | null;
  storybookUrl?: string | null;
  documentationUrl?: string | null;
  repositoryUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Заголовки, описания и OG-картинки для главной, каталога и дефолтов портала. Пустые поля — встроенные значения по умолчанию.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-seo".
 */
export interface PortalSeo {
  id: number;
  siteName?: string | null;
  /**
   * Когда у страницы нет своего title.
   */
  titleDefault?: string | null;
  /**
   * Next.js metadata template, %s — title страницы.
   */
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  locale?: string | null;
  /**
   * Статический файл public/og/portal-site.webp (npm run generate:portal-site-og). Поле не влияет на OG — картинка всегда portal-site.webp.
   */
  defaultOgImage?: (number | null) | Media;
  homeShareTitle?: string | null;
  homeShareDescription?: string | null;
  /**
   * Не используется — OG-картинка всегда public/og/portal-site.webp.
   */
  homeShareImage?: (number | null) | Media;
  catalogWebShareTitle?: string | null;
  catalogWebShareDescription?: string | null;
  /**
   * Не используется — OG-картинка всегда public/og/portal-site.webp.
   */
  catalogWebShareImage?: (number | null) | Media;
  showcaseShareTitle?: string | null;
  showcaseShareDescription?: string | null;
  /**
   * Не используется — OG-картинка всегда public/og/portal-site.webp.
   */
  showcaseShareImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Заголовок, вводный текст и принципы на странице /text/glossary. Сами термины — коллекция «Глоссарий — термины».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "text-glossary".
 */
export interface TextGlossary {
  id: number;
  title?: string | null;
  intro?: string | null;
  principlesHeading?: string | null;
  /**
   * Нумерованный список под заголовком «Как мы выбираем слова».
   */
  principles?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  principlesFooter?: string | null;
  /**
   * Заголовок над таблицей терминов из коллекции.
   */
  termsSectionHeading?: string | null;
  shareTitle?: string | null;
  shareDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Заголовок и вводный текст на странице /brand. Карточки разделов — из коллекции «Brand · Страницы».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-overview".
 */
export interface BrandOverview {
  id: number;
  title?: string | null;
  intro?: string | null;
  shareTitle?: string | null;
  shareDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Секции «Обзор» и «Источники» на странице /ds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ds-overview".
 */
export interface DsOverview {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  lead?: string | null;
  capabilitiesHeading?: string | null;
  installationHeading?: string | null;
  installationIntro?: string | null;
  packageName?: string | null;
  packageVersion?: string | null;
  installCommands?:
    | {
        command: string;
        id?: string | null;
      }[]
    | null;
  setupCode?: string | null;
  /**
   * Markdown отображается на /ds и передаётся ИИ-агенту через finam-design-system MCP.
   */
  usageGuideMarkdown?: string | null;
  capabilities?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stackHeading?: string | null;
  stackItems?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  navigationNote?: string | null;
  roadmapHeading?: string | null;
  roadmap?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  sourcesHeading?: string | null;
  sourcesIntro?: string | null;
  sourceItems?:
    | {
        label: string;
        description?: string | null;
        href: string;
        icon?: ('figma' | 'github' | 'storybook' | 'docs' | 'markdown' | 'link') | null;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-sources_select".
 */
export interface PortalSourcesSelect<T extends boolean = true> {
  figmaLibraryUrl?: T;
  storybookUrl?: T;
  documentationUrl?: T;
  repositoryUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-seo_select".
 */
export interface PortalSeoSelect<T extends boolean = true> {
  siteName?: T;
  titleDefault?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  locale?: T;
  defaultOgImage?: T;
  homeShareTitle?: T;
  homeShareDescription?: T;
  homeShareImage?: T;
  catalogWebShareTitle?: T;
  catalogWebShareDescription?: T;
  catalogWebShareImage?: T;
  showcaseShareTitle?: T;
  showcaseShareDescription?: T;
  showcaseShareImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "text-glossary_select".
 */
export interface TextGlossarySelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  principlesHeading?: T;
  principles?:
    | T
    | {
        text?: T;
        id?: T;
      };
  principlesFooter?: T;
  termsSectionHeading?: T;
  shareTitle?: T;
  shareDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-overview_select".
 */
export interface BrandOverviewSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  shareTitle?: T;
  shareDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ds-overview_select".
 */
export interface DsOverviewSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  capabilitiesHeading?: T;
  installationHeading?: T;
  installationIntro?: T;
  packageName?: T;
  packageVersion?: T;
  installCommands?:
    | T
    | {
        command?: T;
        id?: T;
      };
  setupCode?: T;
  usageGuideMarkdown?: T;
  capabilities?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stackHeading?: T;
  stackItems?:
    | T
    | {
        label?: T;
        id?: T;
      };
  navigationNote?: T;
  roadmapHeading?: T;
  roadmap?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sourcesHeading?: T;
  sourcesIntro?: T;
  sourceItems?:
    | T
    | {
        label?: T;
        description?: T;
        href?: T;
        icon?: T;
        external?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}