/**
 * Генерирует Storybook stories для компонентов ui-kit без ручных stories.
 * Запуск: npm run generate:ds-stories
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { RADIX_THEMES_CATALOG } from "../lib/portal/components/catalog";
import {
  MANUAL_DS_STORY_SLUGS,
  storyPreviewSpecForSlug,
} from "../lib/storybook/ds-story-preview-spec";
import { UI_KIT_CATALOG } from "../packages/ui-kit/src/catalog";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, "..");
const storiesDir = path.join(projectRoot, "components", "ds");

const nameBySlug = new Map(RADIX_THEMES_CATALOG.map((entry) => [entry.slug, entry.name]));

function buildStoryFile(slug: string, exportName: string, displayName: string): string {
  const spec = storyPreviewSpecForSlug(slug, exportName);
  const extraImports = spec.extraImports ?? [];
  const radixImports = [...new Set(extraImports)].sort().join(", ");
  const radixImportLine = radixImports ? `import { ${radixImports} } from "@radix-ui/themes";\n` : "";
  const metaComponent = spec.metaComponent ?? exportName;
  const metaArgsBlock = spec.metaArgs ? `\n  args: ${spec.metaArgs},` : "";

  return `// @generated by generate-ds-stories — do not edit by hand
import type { Meta, StoryObj } from "@storybook/react";
${radixImportLine}import { relatedPreviewDecorator, relatedPreviewStoryParameters } from "@/lib/storybook/related-preview-story";

import { ${exportName} } from "@next-app/ui-kit";

const meta = {
  title: "Design System/${displayName}",
  component: ${metaComponent},${metaArgsBlock}
  tags: ["autodocs"],
  parameters: { layout: "centered" },
} satisfies Meta<typeof ${metaComponent}>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (${spec.defaultBody}),
};

export const RelatedPreview: Story = {
  render: () => (${spec.relatedPreviewBody}),
  parameters: relatedPreviewStoryParameters,
  decorators: [relatedPreviewDecorator],
};
`;
}

let created = 0;
let skipped = 0;

for (const entry of UI_KIT_CATALOG) {
  const slug = entry.slug;
  if (MANUAL_DS_STORY_SLUGS.has(slug)) {
    skipped += 1;
    continue;
  }

  const exportName = entry.exportName;
  const displayName = nameBySlug.get(slug) ?? exportName;
  const storyPath = path.join(storiesDir, `${slug}.stories.tsx`);
  fs.writeFileSync(storyPath, buildStoryFile(slug, exportName, displayName), "utf8");
  created += 1;
}

console.log(`Generated ${created} stories, skipped ${skipped} manual.`);
